### ISSUE TITLE
`/devices`エンドポイントの実装

### ISSUE THREAD

**Issue by Prokuma** [Prokuma/IoT-matsuri-web-backend#2]
`/devices`のエンドポイントの実装が仮実装になっている。書いた仕様書通りに動作するようにエンドポイントを書く。
仕様書はGoogle Driveの第3回会議を参考にしてほしい。

**Comment by Simo-C3** [comment]
@Prokuma redisを使ったやり取りでなんのデータのやり取りをするんでしたっけ？
あと、IoT側のサーバーのローカルでのビルドの方法が分かりません。

**Comment by Prokuma** [comment]
redisは`message`をWebサーバー側のAPIを叩いて送信した場合にIoTサーバの方に投げるときに使います。~~今回の`/devices`エンドポイントとは関係ありません。~~　実装しているのを確認しました。やりとりの方法については次の会議で決めるので今実装する必要はありません。また、IoTサーバの実装が間に合ってません。申し訳ないです。
IoT側のサーバーのビルドには`conan`が必要となります。インストールした後にREADME.mdに書いてあるとおりにビルドすればいいはずです。ビルドで生成済みのファイルは`build/bin`の中に入ります。
